credentials('github-token')

pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
    - name: git
      image: alpine/git
      command: ["cat"]
      tty: true
"""
    }
  }

  environment {
    ECR_REGISTRY = "377728961694.dkr.ecr.us-east-1.amazonaws.com"
    IMAGE_NAME   = "django-app"
    IMAGE_TAG    = "v1.0.${BUILD_NUMBER}"
    GITHUB_USER = credentials('github-token')
    GIT_BRANCH = "final-project"
    COMMIT_EMAIL = "jenkins@localhost"
    COMMIT_NAME  = "jenkins"
  }

  stages {
    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
            cd django-app
            cat goit/settings.py | grep ALLOWED_HOSTS
            /kaniko/executor \\
              --context `pwd` \\
              --dockerfile `pwd`/Dockerfile \\
              --destination=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \\
              --cache=true \\
              --insecure \\
              --skip-tls-verify
          '''
        }
      }
    }

    stage('Update Chart Tag in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PAT')]) {
            sh '''
              echo "User: $GIT_USER"
              echo "PAT: $GIT_PAT"
              git clone --branch $GIT_BRANCH https://$GIT_USER:$GIT_PAT@github.com/nickunderhill/my-microservice-project.git
              cd my-microservice-project/charts

              sed -i "s/tag: .*/tag: $IMAGE_TAG/" values.yaml

              git config user.email "$COMMIT_EMAIL"
              git config user.name "$COMMIT_NAME"

              git add values.yaml
              git commit -m "Update image tag to $IMAGE_TAG"
              git remote set-url origin https://$GIT_USER:$GIT_PAT@github.com/nickunderhill/my-microservice-project.git
              git push origin HEAD
            '''
          }
        }
      }
    }
  }
}
